FROM hermsi/ark-server:latest-1669698243

COPY Game.ini /app/server/ShooterGame/Saved/Config/LinuxServer/Game.ini
COPY GameUserSettings.ini /app/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
COPY instances/ /app/arkmanager/instances/

